name: Build Container
on:
  push:
    branches: [main]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/palworld/server
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          file: ./Containerfile
          tags: |
            ${{ env.IMAGE_TAG }}:${{ github.sha }}
            ${{ env.IMAGE_TAG }}:latest
          push: true
